Forms/Forms/Models/ErrorViewModel.cs
namespace Forms.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Forms/Forms/Models/Libro/LibroCreateModel.cs
using System.ComponentModel.DataAnnotations;

namespace Forms.Models.Libro
{
    public class LibroCreateModel
    {
        [Required(ErrorMessage = "No te olvides del Nombre")]
        [StringLength(5, ErrorMessage = "solo se aceptan 5 letras")]
        public string Nombre { get; set; } = null!;
        public string Editorial { get; set; } = null!;
        public string NoCopias { get; set; } = null!;
    }
}

Forms/Forms/Models/Libro/LibroRegisterModel.cs
namespace Forms.Models.Libro
{
    public class LibroRegisterModel
    {
        public List<LibroCreateModel> LibrosToCreate { get; set; } = null!;
    }
}

Forms/Forms/Controllers/HomeController.cs
using Forms.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Forms.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Forms/Forms/Controllers/LibroController.cs
using Forms.Models.Libro;
using Microsoft.AspNetCore.Mvc;

namespace Forms.Controllers
{
    public class LibroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            List<LibroCreateModel> lista =  new List<LibroCreateModel>();

            lista.Add(new LibroCreateModel
            {
                Nombre = "libro 1"
            });
            lista.Add(new LibroCreateModel
            {
                Nombre = "libro 2"
            });
            lista.Add(new LibroCreateModel
            {
                Nombre = "libro 3"
            });
            return View(new LibroRegisterModel
            {
                LibrosToCreate = lista

            });
        }
        [HttpPost]
        public IActionResult Registrar(LibroRegisterModel lista)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(lista);
            //}
            return View(lista);
        }
        //[HttpPost]
        //public IActionResult Registrar(List<LibroCreateModel> lista)
        //{
        //    return View(lista);
        //}
    }
}

Forms/Forms/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Forms/Forms/Views/Libro/Index.cshtml
<h1>index for libro</h1>
<form ></form>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Editorial</th>
            <th>No.Copias</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <input name="nombre" type="text" placeholder="nombre" />
            </td>
            <td>
                <input name="editorial" type="text" placeholder="editorial" />
            </td>
            <td>
                <input name="no_copias" type="text" placeholder="Numero de copias" />
            </td>
        </tr>
        <tr>
            <td>
                <input name="nombre" type="text" placeholder="nombre" />
            </td>
            <td>
                <input name="editorial" type="text" placeholder="editorial" />
            </td>
            <td>
                <input name="no_copias" type="text" placeholder="Numero de copias" />
            </td>
        </tr>
        <tr>
            <td>
                <input name="nombre" type="text" placeholder="nombre" />
            </td>
            <td>
                <input name="editorial" type="text" placeholder="editorial" />
            </td>
            <td>
                <input name="no_copias" type="text" placeholder="Numero de copias" />
            </td>
        </tr>
        <tr>
            <td>
                <input name="nombre" type="text" placeholder="nombre" />
            </td>
            <td>
                <input name="editorial" type="text" placeholder="editorial" />
            </td>
            <td>
                <input name="no_copias" type="text" placeholder="Numero de copias" />
            </td>
        </tr>
    </tbody>
</table>

Forms/Forms/Views/Libro/Registrar.cshtml
@model Forms.Models.Libro.LibroRegisterModel

@{
    ViewData["Title"] = "Registrar";
}

<h1>Registrar</h1>

<h4>LibroCreateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Registrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <table>
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Editorial</th>
                        <th>No.Copias</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.LibrosToCreate.Count; i++)
                                {
                        <tr>
                            <td>
                                <input asp-for="LibrosToCreate[i].Nombre" type="text" placeholder="nombre" />
                            </td>
                            <td>
                                <input asp-for="LibrosToCreate[i].Editorial" type="text" placeholder="editorial" />
                            </td>
                            <td>
                                <input asp-for="LibrosToCreate[i].NoCopias" type="text" placeholder="Numero de copias" />
                            </td>
                        </tr> 
                        
                    }
                   
                </tbody>
            </table>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forms/Forms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Forms.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Forms</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="Registrar">Registrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Forms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>